### ISSUE TITLE
Deprecated: Function get_magic_quotes_gpc() in PHP 7.4

### ISSUE THREAD

**Issue by ghost** [pear/HTML_QuickForm2#3]
Deprecated: Function `get_magic_quotes_gpc()` is deprecated in /usr/share/php/HTML/QuickForm2.php on line 85

see https://www.php.net/manual/en/function.get-magic-quotes-gpc.php

possible solution in line:85
replace  
```
            $this->addDataSource(new HTML_QuickForm2_DataSource_SuperGlobal(
                $method, get_magic_quotes_gpc()
            )); 
```
with
```
            $this->addDataSource(new HTML_QuickForm2_DataSource_SuperGlobal(
                $method, false
            )); 
```

**Comment by sad-spirit** [comment]
@golgote what's your take on this? Should we remove magic_quotes_gpc support and up the PHP requirement to 5.4 or try to add some kind of workaround for PHP 7.4+?

**Comment by golgote** [comment]
@sad-spirit I suggest that we up the php version requirement to 5.4 and remove it. Thanks
