### ISSUE TITLE
Need to fix PSR-4 Autoloading for related package

### ISSUE THREAD

**Issue by TheMY3** [pear/HTML_QuickForm2#4]
Can not install HTML/QuickForm2 via Composer 2, the problem is that Composer 1 should be deprecated in few months. Need to split tests in package https://github.com/pear/HTML_Common2 to own files as in this package to fix it.

Now I go errors:
```
Class HTML_Common2_Concrete located in ./vendor/pear/html_common2/tests/HTML_Common2_Test.php does not comply with psr-0 autoloading standard. Skipping.
Class HTML_Common2_WatchedAttributes located in ./vendor/pear/html_common2/tests/HTML_Common2_Test.php does not comply with psr-0 autoloading standard. Skipping.
Class HTML_Common2_Test located in ./vendor/pear/html_common2/tests/HTML_Common2_Test.php does not comply with psr-0 autoloading standard. Skipping.
Class HTML_Common2_AllTests located in ./vendor/pear/html_common2/tests/AllTests.php does not comply with psr-0 autoloading standard. Skipping.
```

P.S. I can not send a bug request to http://pear.php.net/package/HTML_Common2 so wrote it here, I can try to create PR to https://github.com/pear/HTML_Common2 if you agree with it.

@sad-spirit can you help with it?

**Comment by golgote** [comment]
Something like this in composer.json :
 
```
"autoload": {
    "exclude-from-classmap": ["/tests/"]
}
```
Or do you suggest something else ?

**Comment by TheMY3** [comment]
@golgote sounds good if it fix PSR-4 autoloading errors and allow to use Composer 2. I thought that it would be necessary to rewrite tests in HTML_Common2 to separate files.

**Comment by TheMY3** [comment]
@sad-spirit @golgote are you planning to fix this soon? Otherwise, I need to migrate to a fork without PEAR dependencies - https://github.com/openpsa/quickform in few months. But I would not want to do this to be honest.

**Comment by sad-spirit** [comment]
@YaroslavMolchan Yep, I'll probably push a new release sometime soon with `.gitattributes` file preventing the installation of tests with composer, as was done with e.g. pear/HTTP_Request2#19

Need to also check whether it is possible to run tests on Github actions using PHP 5.x, I want to get rid of Travis but obviously don't want to make releases without CI.

**Comment by golgote** [comment]
Hi @sad-spirit, what's wrong with using the following in composer.json ?
```
"autoload": {
    "exclude-from-classmap": ["/tests/"]
}
```

**Comment by sad-spirit** [comment]
@golgote - there's nothing wrong with that, just the current recommendation for composer packages is not to include tests in installation: https://php.watch/articles/composer-gitattributes

**Comment by golgote** [comment]
OK cool, so maybe you could add both ? Because for me, the change to .gitattributes didn't silence the composer deprecation warnings while the exclude directive did. Thanks !

**Comment by TheMY3** [comment]
@sad-spirit @golgote is there any info for this issue?

**Comment by golgote** [comment]
I've made https://github.com/pear/HTML_QuickForm2/pull/5 if you want to review it.

**Comment by TheMY3** [comment]
> I've made #5 if you want to review it.

Oh, thank you, but errors was with related repository -  https://github.com/pear/HTML_Common2
```
Class HTML_Common2_Concrete located in ./vendor/pear/html_common2/tests/HTML_Common2_Test.php does not comply with psr-0 autoloading standard. Skipping.
Class HTML_Common2_WatchedAttributes located in ./vendor/pear/html_common2/tests/HTML_Common2_Test.php does not comply with psr-0 autoloading standard. Skipping.
Class HTML_Common2_Test located in ./vendor/pear/html_common2/tests/HTML_Common2_Test.php does not comply with psr-0 autoloading standard. Skipping.
Class HTML_Common2_AllTests located in ./vendor/pear/html_common2/tests/AllTests.php does not comply with psr-0 autoloading standard. Skipping.
```
Are you sure that `exclude-from-classmap` should be placed here, not in https://github.com/pear/HTML_Common2?

**Comment by sad-spirit** [comment]
I released a new version of HTML_Common2, tests will no longer be installed with it. I also (hopefully) fixed autoloading for these when checking out from git by using `classmap` instead of `psr-0`.

Github Issues are now enabled for HTML_Common2, so please report there if something is still not working as expected.

**Comment by TheMY3** [comment]
@sad-spirit thank you, can you please release new version with updated https://github.com/pear/HTML_Common2 -  https://github.com/pear/HTML_QuickForm2/blob/trunk/composer.json#L29

HTML_QuickForm2 used 2.1 version for now, but need to change version to 2.2.

**Comment by thedotedge** [comment]
Hey! Any chance you could cut a new tag @sad-spirit? 🙇🏻

**Comment by sad-spirit** [comment]
@YaroslavMolchan @thedotedge That's not strictly necessary as composer will install the latest compatible version anyway, but I'll try to do a release this weekend

**Comment by sad-spirit** [comment]
Release 2.2.1 done
