### ISSUE TITLE
Any ideas to implement PHP 8.1 support?

### ISSUE THREAD

**Issue by TheMY3** [pear/HTML_QuickForm2#6]
Any ideas to implement PHP 8.1 support?
Do you have opportunity or time for it? I can help with implementation if you want.

**Comment by sad-spirit** [comment]
> Any ideas to implement PHP 8.1 support?

In fact, there are some: first the test suite should be upgraded using [PHPUnit-polyfills package](https://github.com/Yoast/PHPUnit-Polyfills) and migrated to Github Actions from Travis. This is similar to what was done in [HTTP_Request2](https://github.com/pear/HTTP_Request2).

I think we can safely drop support for PHP below 5.6 at this point, @golgote --- do you agree?

After we have a test suite running on 8.1, fixing the package itself will probably be trivial.

> I can help with implementation if you want.

Well, if you are willing to do the test suite migration then welcome aboard!

**Comment by thedotedge** [comment]
hi @sad-spirit, any chance you'd be proceeding with implementation soon?

**Comment by sychova-fh** [comment]
Hello, @sad-spirit. I'm looking for the same solution with PHP 8.1 support! My code is ready to support 8.1 but due to the use of HTML_QuickForm2, I can't do it. Is there any chance of PHP 8.1 support coming soon? I wouldn't want to look for an alternative to HTML_QuickForm2 right now. But soon I'll have no choice.

**Comment by sad-spirit** [comment]
@thedotedge , @sychova-fh I'm currently working on upgrading the test suite, will probably finish in a few days.

**Comment by sad-spirit** [comment]
Please test the current HEAD with your code: I fixed all `E_DEPRECATED` messages that appear when running tests on PHP 8.1. Please let me know whether there are other places with these appearing.

**Comment by sychova-fh** [comment]
@sad-spirit Thank you so much for your work! I will test it ASAP

**Comment by thedotedge** [comment]
Some warnings when running tests (not a blocker):

```
php -v
PHP 8.1.3
```

```
Warning:       Test case class not matching filename is deprecated
               in /Projects/other/HTML_QuickForm2/tests/QuickForm2/Rule/MaxFileSizeTest.php
               Class name was 'HTML_QuickForm2_Rule_MaxFileSizeTest', expected 'MaxFileSizeTest'
Warning:       Test case class not matching filename is deprecated
               in /Projects/other/HTML_QuickForm2/tests/QuickForm2/Rule/MimeTypeTest.php
               Class name was 'HTML_QuickForm2_Rule_MimeTypeTest', expected 'MimeTypeTest'
Warning:       Test case class not matching filename is deprecated
               in /Projects/other/HTML_QuickForm2/tests/QuickForm2/Rule/NonemptyTest.php
               Class name was 'HTML_QuickForm2_Rule_NonemptyTest', expected 'NonemptyTest'
Warning:       Test case class not matching filename is deprecated
               in /Projects/other/HTML_QuickForm2/tests/QuickForm2/Rule/NotCallbackTest.php
               Class name was 'HTML_QuickForm2_Rule_NotCallbackTest', expected 'NotCallbackTest'
Warning:       Test case class not matching filename is deprecated
```

**Comment by sad-spirit** [comment]
Version 2.3.0 released. Since test suite runs OK and psalm doesn't find any problems on reasonable level let's hope there are no more problems on PHP 8.1
