### ISSUE TITLE
PHP 8.1: Several deprecation notices for strlen

### ISSUE THREAD

**Issue by alexgit2k** [pear/HTML_QuickForm2#7]
With PHP 8.1 there are several deprecation notices for strlen when passing null as parameter:
- https://github.com/pear/HTML_QuickForm2/blob/4ef4051dca6d34cf434795f134ba24aa59185ab5/HTML/QuickForm2/Element/InputCheckable.php#L130
- https://github.com/pear/HTML_QuickForm2/blob/4ef4051dca6d34cf434795f134ba24aa59185ab5/HTML/QuickForm2/Element/InputHidden.php#L65
- https://github.com/pear/HTML_QuickForm2/blob/4ef4051dca6d34cf434795f134ba24aa59185ab5/HTML/QuickForm2/Element/Date.php#L162

### Example
```
docker run -it --rm php:8.1 /bin/bash

apt-get update -yqq && apt-get install -y git
curl https://getcomposer.org/download/latest-stable/composer.phar > /usr/local/bin/composer
chmod a+rx /usr/local/bin/composer
composer require pear/html_quickform2:dev-trunk

cat <<EOT > test.php
<?php
require_once('vendor/autoload.php');

\$checkable = new HTML_QuickForm2_Element_InputCheckable('foo', null, ['content' => null]);
print \$checkable;

\$input = new HTML_QuickForm2_Element_InputHidden();
\$input->setError(null);

\$date = new HTML_QuickForm2_Element_Date('foo', null, ['format' => null]);
EOT

php test.php
```

### Output
```
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /vendor/pear/html_quickform2/HTML/QuickForm2/Element/InputCheckable.php on line 130

Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /vendor/pear/html_quickform2/HTML/QuickForm2/Element/InputHidden.php on line 65

Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /vendor/pear/html_quickform2/HTML/QuickForm2/Element/Date.php on line 162
```

**Comment by sad-spirit** [comment]
The first two problems are real, the last one seems bogus: passing `null` as `'format'` argument will create a non-working `Date` element anyway.

BTW, I'm currently trying to setup static analysis using psalm and it seems to catch the above problems on high enough level.
