### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'HTML_QuickForm2_Container' not found

### ISSUE THREAD

**Issue by beckspaced** [pear/HTML_QuickForm2#9]
Hello there,

recently did an upgrade on HTML_QuickForm2 latest stable version 2.3.0

After updating the following shows up in the log

`[23-May-2022 07:56:22 UTC] PHP Fatal error:  Uncaught Error: Class 'HTML_QuickForm2_Container' not found in /usr/share/php7/PEAR/HTML/QuickForm2.php:43
Stack trace:
#0 /srv/www/domain/httpdocs/includes/global_inc.php(11): require_once()
#1 /srv/www/domain/httpdocs/module.php(2): include_once('/srv/www/domain...')
#2 {main}
  thrown in /usr/share/php7/PEAR/HTML/QuickForm2.php on line 43`
  
reverting back to version 2.2.2 all is working fine again.

I'm running an OpenSuSE Box 15.3 with apache and php fpm 7.4.6

any advice on how to fix this would be great :)

thanks
& all the best
Becki

**Comment by sad-spirit** [comment]
Oops, looks like I messed up the PEAR release, it does not have `require_once` statements re-enabled.

**Comment by sad-spirit** [comment]
Released version 2.3.1, it should properly work when installed with PEAR. Sorry for the f***up.

**Comment by beckspaced** [comment]
thanks, that did the trick!
quickform2 working again :)
